// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACI0nlGN5xDHp6ChF3fUuztXCfOvfFyRE',
    appId: '1:37376458722:web:d33642f0831dfbf8aa43bb',
    messagingSenderId: '37376458722',
    projectId: 'giftifybase',
    authDomain: 'giftifybase.firebaseapp.com',
    storageBucket: 'giftifybase.appspot.com',
    measurementId: 'G-KXNEJBV95B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxKlC7Ksbv7gR4CW8UGkSnYFXRW1bUugY',
    appId: '1:37376458722:android:a2466e31e99a09f4aa43bb',
    messagingSenderId: '37376458722',
    projectId: 'giftifybase',
    storageBucket: 'giftifybase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_3OmLUYafJOpsUsUUDCsXXLMjLBYoVA',
    appId: '1:37376458722:ios:058e9cee3ec5afc8aa43bb',
    messagingSenderId: '37376458722',
    projectId: 'giftifybase',
    storageBucket: 'giftifybase.appspot.com',
    iosBundleId: 'com.example.giftify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp_3OmLUYafJOpsUsUUDCsXXLMjLBYoVA',
    appId: '1:37376458722:ios:058e9cee3ec5afc8aa43bb',
    messagingSenderId: '37376458722',
    projectId: 'giftifybase',
    storageBucket: 'giftifybase.appspot.com',
    iosBundleId: 'com.example.giftify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACI0nlGN5xDHp6ChF3fUuztXCfOvfFyRE',
    appId: '1:37376458722:web:d0d884fc03175c19aa43bb',
    messagingSenderId: '37376458722',
    projectId: 'giftifybase',
    authDomain: 'giftifybase.firebaseapp.com',
    storageBucket: 'giftifybase.appspot.com',
    measurementId: 'G-R3BN5YYLY7',
  );
}
